import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import { SessionWrapper } from "@/utils/session-provider";
import { Toaster } from "@/components/ui/toaster";
// import CustomProvider from "@/components/common/progressBarProvider/progressBarProvider";
import { Providers } from "@/components/common/store-provider/store-provider";

const nunito = Nunito({ subsets: ['latin'], weight: ['300', '400', '600', '700'] })




export const metadata: Metadata = {
  title: "ChatBot Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/main-logo.svg" sizes="any" />
        {/* You can add more meta tags here if needed */}
      </head>
      <body
        className={` ${nunito.className} antialiased`}
      >
        <SessionWrapper>
          <Providers>{children}</Providers>
        </SessionWrapper>
        <Toaster />
      </body>
    </html>
  );
}
